# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(290, 500)
        mainWindow.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(43, 41, 42);\n"
"color: rgb(255, 255, 255);\n"
"padding: 25;")
        self.label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.label.setObjectName("label")
        self.equals = QtWidgets.QPushButton(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(220, 349, 60, 131))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.equals.setFont(font)
        self.equals.setMouseTracking(False)
        self.equals.setAcceptDrops(False)
        self.equals.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.equals.setStyleSheet("border-radius: 10px;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0.45 rgba(2, 165, 170, 255), stop:1 rgba(7, 240, 255, 233));\n"
"color: rgb(255, 255, 255);")
        self.equals.setAutoDefault(False)
        self.equals.setDefault(False)
        self.equals.setFlat(False)
        self.equals.setObjectName("equals")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(220, 280, 60, 60))
        self.plus.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.plus.setFont(font)
        self.plus.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.plus.setObjectName("plus")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(150, 140, 60, 60))
        self.multiply.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.multiply.setObjectName("multiply")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(220, 140, 60, 60))
        self.divide.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.divide.setFont(font)
        self.divide.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.divide.setObjectName("divide")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(10, 140, 60, 60))
        self.clear.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.clear.setFont(font)
        self.clear.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.clear.setObjectName("clear")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(220, 210, 60, 60))
        self.minus.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.minus.setFont(font)
        self.minus.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.minus.setObjectName("minus")
        self.percent = QtWidgets.QPushButton(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(80, 140, 60, 60))
        self.percent.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.percent.setFont(font)
        self.percent.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(11,66,86);")
        self.percent.setObjectName("percent")
        self.zero = QtWidgets.QPushButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(10, 420, 130, 60))
        self.zero.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.zero.setFont(font)
        self.zero.setMouseTracking(False)
        self.zero.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.zero.setObjectName("zero")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(150, 420, 60, 60))
        self.dot.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.dot.setFont(font)
        self.dot.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.dot.setObjectName("dot")
        self.one = QtWidgets.QPushButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 350, 60, 60))
        self.one.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.one.setFont(font)
        self.one.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.one.setFlat(False)
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(80, 350, 60, 60))
        self.two.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.two.setFont(font)
        self.two.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(150, 350, 60, 60))
        self.three.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.three.setFont(font)
        self.three.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.three.setObjectName("three")
        self.four = QtWidgets.QPushButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 280, 60, 60))
        self.four.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.four.setFont(font)
        self.four.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(80, 280, 60, 60))
        self.five.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.five.setFont(font)
        self.five.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(150, 280, 60, 60))
        self.six.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.six.setFont(font)
        self.six.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 210, 60, 60))
        self.seven.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.seven.setFont(font)
        self.seven.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(80, 210, 60, 60))
        self.eight.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.eight.setFont(font)
        self.eight.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(150, 210, 60, 60))
        self.nine.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.nine.setFont(font)
        self.nine.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(52,52,52);")
        self.nine.setObjectName("nine")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Калькулятор"))
        self.label.setText(_translate("mainWindow", "0"))
        self.equals.setText(_translate("mainWindow", "="))
        self.plus.setText(_translate("mainWindow", "+"))
        self.multiply.setText(_translate("mainWindow", "*"))
        self.divide.setText(_translate("mainWindow", "/"))
        self.clear.setText(_translate("mainWindow", "C"))
        self.minus.setText(_translate("mainWindow", "-"))
        self.percent.setText(_translate("mainWindow", "%"))
        self.zero.setText(_translate("mainWindow", "0"))
        self.dot.setText(_translate("mainWindow", "."))
        self.one.setText(_translate("mainWindow", "1"))
        self.two.setText(_translate("mainWindow", "2"))
        self.three.setText(_translate("mainWindow", "3"))
        self.four.setText(_translate("mainWindow", "4"))
        self.five.setText(_translate("mainWindow", "5"))
        self.six.setText(_translate("mainWindow", "6"))
        self.seven.setText(_translate("mainWindow", "7"))
        self.eight.setText(_translate("mainWindow", "8"))
        self.nine.setText(_translate("mainWindow", "9"))

    def add_functions(self):
        self.zero.clicked.connect(lambda: self.write_number(self.zero.text()))
        self.one.clicked.connect(lambda: self.write_number(self.one.text()))
        self.two.clicked.connect(lambda: self.write_number(self.two.text()))
        self.three.clicked.connect(lambda: self.write_number(self.three.text()))
        self.four.clicked.connect(lambda: self.write_number(self.four.text()))
        self.five.clicked.connect(lambda: self.write_number(self.five.text()))
        self.six.clicked.connect(lambda: self.write_number(self.six.text()))
        self.seven.clicked.connect(lambda: self.write_number(self.seven.text()))
        self.eight.clicked.connect(lambda: self.write_number(self.eight.text()))
        self.nine.clicked.connect(lambda: self.write_number(self.nine.text()))
        self.plus.clicked.connect(lambda: self.write_number(self.plus.text()))
        self.multiply.clicked.connect(lambda: self.write_number(self.multiply.text()))
        self.divide.clicked.connect(lambda: self.write_number(self.divide.text()))
        self.minus.clicked.connect(lambda: self.write_number(self.minus.text()))
        self.percent.clicked.connect(lambda: self.write_number(self.percent.text()))
        self.dot.clicked.connect(lambda: self.write_number(self.dot.text()))
        self.clear.clicked.connect(lambda: self.label.setText("0"))

        self.equals.clicked.connect(self.results)

    def write_number(self, number):
        if self.label.text() == "0" or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)

    def results(self):
        res = eval(self.label.text())
        self.label.setText(str(res))
        self.is_equal = True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
